model:
  latent_dim: 16
  rvq_levels: 4
  codebook_size: 1024
  commit_weight: 0.25
  temp: 1.0
  horizons: [1, 2, 4, 8]
  future_pred_weight: 1.0
  type: fpt

dataset:
  root: data/video
  name: Gymnasium_CartPole
  split: train
  clip_len: 16
  resolution: 64

training:
  epochs: 10
  steps_per_epoch: 20
  batch_size: 2
  lr: 3e-4
  num_workers: 0
  seed: 42
  out_dir: runs/fpt_model
  log_interval: 2
  save_interval: 10